### ISSUE TITLE
Info on standard esxi export

### ISSUE THREAD

**Issue by docop** [gngordon/Export-VMs-to-OVA#1]
Hi  I find your idea quite great to get the so easy function back from v6. So on a esxi 6.7 host itself.. Can it be done as well ?  And is it possible to like run the script and that get the data vm name automatically and then choose the one to export to ova ?
Thanks in advance

**Comment by gngordon** [comment]
Hi, Not quite clear on your question on 6 and 6.7?

The script was written to allow the user to interact and select the VMs they want from the entries in the CSV text file. You could alter the script so that it just selects all the entries and just runs a the Export-VApp on them.

If you strip the logic away this is really only running the following commands
```
$vmrecord = Get-VM -Name $vm.Name
$vmrecord | Export-VApp -Destination $Export_Directory -Format Ova -Force
```

**Comment by docop** [comment]
thanks for precision.
